# Generated by Django 5.1.4 on 2025-06-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_interview_updated_at_question_is_generated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='ai_feedback',
        ),
        migrations.RemoveField(
            model_name='response',
            name='video_url',
        ),
    ]
