# Generated by Django 5.1.4 on 2025-06-24 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_response_ai_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='response',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='response',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='response',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='interview',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.interview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.TextField(default='placeholder'),
            preserve_default=False,
        ),
    ]
