# Generated by Django 5.1.4 on 2025-06-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_question_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
