from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.utils import timezone

# Custom User Manager
class UserManager(BaseUserManager):
    def create_user(self, email, username, supabase_id=None, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, supabase_id=supabase_id, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, supabase_id=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, username, supabase_id, password, **extra_fields)

# Custom User Model
class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=255, unique=True)
    supabase_id = models.CharField(max_length=36, unique=True, null=True)  # Supabase UUID
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        db_table = 'api_user'

    def __str__(self):
        return self.email

# Resume Model
class Resume(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField(null=True, blank=True)
    file_url = models.URLField()

# Interview Model
class Interview(models.Model):
    LEVEL_CHOICES = [
        ('ENTRY', 'Entry Level'),
        ('INTERMEDIATE', 'Intermediate'),
        ('SENIOR', 'Senior'),
    ]

    MODE_CHOICES = [
        ('REAL', 'Real Mode'),
        ('PRACTICE', 'Practice Mode'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='interviews')
    title = models.CharField(max_length=200, default="General Interview")
    scheduled_at = models.DateTimeField(null=True, blank=True)
    level = models.CharField(max_length=20, choices=LEVEL_CHOICES)
    mode = models.CharField(max_length=20, choices=MODE_CHOICES)
    duration_seconds = models.IntegerField()  # Duration in seconds
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.title} for {self.user.username} at {self.scheduled_at}"

# Question Model
class Question(models.Model):
    interview = models.ForeignKey(Interview, on_delete=models.CASCADE, related_name='questions')
    text = models.TextField()
    order = models.IntegerField()  # To maintain question sequence
    is_generated = models.BooleanField(default=True)  # Flag if generated by LLM
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('interview', 'order')

    def __str__(self):
        return f"Question {self.order} for {self.interview}"

# Response Model
class Response(models.Model):
    question = models.OneToOneField(Question, on_delete=models.CASCADE, related_name='response')
    text = models.TextField(blank=True, null=True)  # User's textual response
    video_url = models.URLField(max_length=500, blank=True, null=True)  # Video response URL
    ai_feedback = models.TextField(blank=True, null=True)  # AI-generated feedback (if any)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Response for {self.question}"
